"""
Script de seeding pour Bor-bi Tech by TransTech Solution
Crée 500+ produits dans 11 catégories
"""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime
import os
from dotenv import load_dotenv
from pathlib import Path

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

mongo_url = os.environ['MONGO_URL']
db_name = os.environ['DB_NAME']

# Catalogue de produits par catégorie (500+ produits)
PRODUCTS_DATA = {
    "boulangerie": [
        {"nameFr": "Pain ordinaire", "nameWolof": "Mburu", "unit": "unité", "price": 150},
        {"nameFr": "Pain au chocolat", "nameWolof": "Pain bu chocola", "unit": "unité", "price": 250},
        {"nameFr": "Croissant", "nameWolof": "Croissant", "unit": "unité", "price": 300},
        {"nameFr": "Baguette", "nameWolof": "Baget", "unit": "unité", "price": 200},
        {"nameFr": "Pain complet", "nameWolof": "Pain complet", "unit": "unité", "price": 250},
        {"nameFr": "Pain de mie", "nameWolof": "Pain de mie", "unit": "paquet", "price": 500},
        {"nameFr": "Brioche", "nameWolof": "Brioche", "unit": "unité", "price": 350},
        {"nameFr": "Tarte aux pommes", "nameWolof": "Tarte", "unit": "unité", "price": 1000},
        {"nameFr": "Gâteau au chocolat", "nameWolof": "Gato", "unit": "part", "price": 500},
        {"nameFr": "Muffin", "nameWolof": "Muffin", "unit": "unité", "price": 400},
        {"nameFr": "Cookie", "nameWolof": "Cookie", "unit": "unité", "price": 200},
        {"nameFr": "Donut", "nameWolof": "Donut", "unit": "unité", "price": 300},
        {"nameFr": "Pain aux raisins", "nameWolof": "Pain bu raisin", "unit": "unité", "price": 250},
        {"nameFr": "Chausson aux pommes", "nameWolof": "Chausson", "unit": "unité", "price": 350},
        {"nameFr": "Éclair au café", "nameWolof": "Eclair", "unit": "unité", "price": 400},
        {"nameFr": "Macaron", "nameWolof": "Macaron", "unit": "unité", "price": 300},
        {"nameFr": "Brownie", "nameWolof": "Brownie", "unit": "unité", "price": 500},
        {"nameFr": "Tarte citron", "nameWolof": "Tarte citron", "unit": "part", "price": 600},
        {"nameFr": "Pain de seigle", "nameWolof": "Pain seigle", "unit": "unité", "price": 300},
        {"nameFr": "Petit pain", "nameWolof": "Petit mburu", "unit": "unité", "price": 100},
    ],
    "frais_proteines": [
        # Poulet
        {"nameFr": "Poulet PAC entier", "nameWolof": "Ginaar PAC", "unit": "kg", "price": 2500, "brand": "PAC"},
        {"nameFr": "Poulet chair entier", "nameWolof": "Ginaar chair", "unit": "kg", "price": 2800, "brand": "Chair"},
        {"nameFr": "Poulet Cayar entier", "nameWolof": "Ginaar Cayar", "unit": "kg", "price": 3000, "brand": "Cayar"},
        {"nameFr": "Cuisses de poulet", "nameWolof": "Tànk ginaar", "unit": "kg", "price": 2200},
        {"nameFr": "Ailes de poulet", "nameWolof": "Làmbaan ginaar", "unit": "kg", "price": 2000},
        {"nameFr": "Blanc de poulet", "nameWolof": "Bërëb ginaar", "unit": "kg", "price": 3500},
        {"nameFr": "Pilons de poulet", "nameWolof": "Pilon ginaar", "unit": "kg", "price": 2100},
        {"nameFr": "Foie de poulet", "nameWolof": "Rës ginaar", "unit": "kg", "price": 1500},
        {"nameFr": "Gésiers de poulet", "nameWolof": "Gesiers ginaar", "unit": "kg", "price": 1800},
        
        # Poissons
        {"nameFr": "Thiof frais", "nameWolof": "Thiof", "unit": "kg", "price": 5000},
        {"nameFr": "Courbine", "nameWolof": "Courbine", "unit": "kg", "price": 3500},
        {"nameFr": "Dorade", "nameWolof": "Dorade", "unit": "kg", "price": 3000},
        {"nameFr": "Capitaine", "nameWolof": "Capitaine", "unit": "kg", "price": 4000},
        {"nameFr": "Sardines fraîches", "nameWolof": "Yaboy", "unit": "kg", "price": 1500},
        {"nameFr": "Maquereau frais", "nameWolof": "Maquereau", "unit": "kg", "price": 1800},
        {"nameFr": "Kéthiakh fumé", "nameWolof": "Kéthiakh", "unit": "kg", "price": 2500},
        {"nameFr": "Sole", "nameWolof": "Sole", "unit": "kg", "price": 3200},
        {"nameFr": "Mérou", "nameWolof": "Mérou", "unit": "kg", "price": 4500},
        {"nameFr": "Bar", "nameWolof": "Bar", "unit": "kg", "price": 3800},
        {"nameFr": "Pageot", "nameWolof": "Pageot", "unit": "kg", "price": 2800},
        {"nameFr": "Thon frais", "nameWolof": "Thon", "unit": "kg", "price": 3500},
        {"nameFr": "Crevettes", "nameWolof": "Crevettes", "unit": "kg", "price": 6000},
        {"nameFr": "Calamars", "nameWolof": "Calamars", "unit": "kg", "price": 4000},
        {"nameFr": "Poulpe", "nameWolof": "Poulpe", "unit": "kg", "price": 3500},
        
        # Viandes
        {"nameFr": "Bœuf (viande)", "nameWolof": "Yàpp mbaam", "unit": "kg", "price": 4000},
        {"nameFr": "Mouton (gigot)", "nameWolof": "Xar", "unit": "kg", "price": 4500},
        {"nameFr": "Chèvre", "nameWolof": "Bëy", "unit": "kg", "price": 3800},
        {"nameFr": "Merguez", "nameWolof": "Merguez", "unit": "kg", "price": 3000},
        {"nameFr": "Saucisses", "nameWolof": "Saucisse", "unit": "kg", "price": 2500},
        
        # Œufs & Lait
        {"nameFr": "Œufs (plateau 30)", "nameWolof": "Nen", "unit": "plateau", "price": 2500},
        {"nameFr": "Lait frais", "nameWolof": "Meew", "unit": "litre", "price": 800},
        {"nameFr": "Yaourt nature", "nameWolof": "Yaourt", "unit": "pot", "price": 300},
        {"nameFr": "Fromage local", "nameWolof": "Fromage", "unit": "kg", "price": 3500},
        {"nameFr": "Beurre", "nameWolof": "Beurre", "unit": "250g", "price": 1500},
        {"nameFr": "Crème fraîche", "nameWolof": "Crème", "unit": "pot", "price": 800},
        {"nameFr": "Lait caillé", "nameWolof": "Lakh", "unit": "litre", "price": 500},
        {"nameFr": "Œufs bio", "nameWolof": "Nen bio", "unit": "douzaine", "price": 1500},
        {"nameFr": "Fromage râpé", "nameWolof": "Fromage râpé", "unit": "sachet", "price": 1200},
        {"nameFr": "Lait concentré", "nameWolof": "Lait concentré", "unit": "boîte", "price": 400},
    ],
    "fruits_legumes": [
        # Fruits
        {"nameFr": "Banane douce", "nameWolof": "Banana", "unit": "kg", "price": 800},
        {"nameFr": "Ananas", "nameWolof": "Ananas", "unit": "unité", "price": 1000},
        {"nameFr": "Mangue", "nameWolof": "Mango", "unit": "kg", "price": 600},
        {"nameFr": "Aviva (pomme cajou)", "nameWolof": "Aviva", "unit": "kg", "price": 500},
        {"nameFr": "Citron", "nameWolof": "Citron", "unit": "kg", "price": 700},
        {"nameFr": "Orange", "nameWolof": "Orange", "unit": "kg", "price": 500},
        {"nameFr": "Clémentine", "nameWolof": "Clémentine", "unit": "kg", "price": 800},
        {"nameFr": "Pomme", "nameWolof": "Pom", "unit": "kg", "price": 1200},
        {"nameFr": "Papaye", "nameWolof": "Papaye", "unit": "kg", "price": 600},
        {"nameFr": "Pastèque", "nameWolof": "Melon d'eau", "unit": "kg", "price": 300},
        {"nameFr": "Melon", "nameWolof": "Melon", "unit": "kg", "price": 500},
        {"nameFr": "Raisin", "nameWolof": "Raisin", "unit": "kg", "price": 2000},
        {"nameFr": "Poire", "nameWolof": "Poire", "unit": "kg", "price": 1500},
        {"nameFr": "Pêche", "nameWolof": "Pêche", "unit": "kg", "price": 1800},
        {"nameFr": "Fraise", "nameWolof": "Fraise", "unit": "barquette", "price": 2000},
        
        # Légumes
        {"nameFr": "Oignon", "nameWolof": "Soble", "unit": "kg", "price": 400},
        {"nameFr": "Ail", "nameWolof": "Lay", "unit": "kg", "price": 1500},
        {"nameFr": "Tomate", "nameWolof": "Tomate", "unit": "kg", "price": 500},
        {"nameFr": "Pomme de terre", "nameWolof": "Patate", "unit": "kg", "price": 400},
        {"nameFr": "Carotte", "nameWolof": "Carotte", "unit": "kg", "price": 500},
        {"nameFr": "Chou", "nameWolof": "Chou", "unit": "kg", "price": 300},
        {"nameFr": "Salade", "nameWolof": "Salade", "unit": "pièce", "price": 200},
        {"nameFr": "Concombre", "nameWolof": "Concombre", "unit": "kg", "price": 400},
        {"nameFr": "Poivron", "nameWolof": "Poivron", "unit": "kg", "price": 800},
        {"nameFr": "Aubergine", "nameWolof": "Aubergine", "unit": "kg", "price": 600},
        {"nameFr": "Haricots verts", "nameWolof": "Haricots", "unit": "kg", "price": 1000},
        {"nameFr": "Courgette", "nameWolof": "Courgette", "unit": "kg", "price": 700},
        {"nameFr": "Navet", "nameWolof": "Navet", "unit": "kg", "price": 300},
        {"nameFr": "Persil", "nameWolof": "Persil", "unit": "botte", "price": 100},
        {"nameFr": "Coriandre", "nameWolof": "Coriandre", "unit": "botte", "price": 100},
    ],
    "epicerie_conserves": [
        {"nameFr": "Riz brisé (sac 50kg)", "nameWolof": "Ceeb brisé", "unit": "sac", "price": 25000},
        {"nameFr": "Riz parfumé (sac 25kg)", "nameWolof": "Ceeb parfumé", "unit": "sac", "price": 18000},
        {"nameFr": "Mil", "nameWolof": "Souna", "unit": "kg", "price": 400},
        {"nameFr": "Maïs", "nameWolof": "Mburu", "unit": "kg", "price": 350},
        {"nameFr": "Fonio", "nameWolof": "Fonio", "unit": "kg", "price": 800},
        {"nameFr": "Semoule", "nameWolof": "Semoule", "unit": "kg", "price": 600},
        {"nameFr": "Couscous", "nameWolof": "Couscous", "unit": "kg", "price": 700},
        {"nameFr": "Pâtes alimentaires", "nameWolof": "Pâtes", "unit": "paquet", "price": 400},
        {"nameFr": "Spaghetti", "nameWolof": "Spaghetti", "unit": "paquet", "price": 350},
        {"nameFr": "Macaroni", "nameWolof": "Macaroni", "unit": "paquet", "price": 400},
        {"nameFr": "Huile végétale (5L)", "nameWolof": "Tuti", "unit": "bidon", "price": 6000},
        {"nameFr": "Huile d'olive (1L)", "nameWolof": "Tuti olive", "unit": "bouteille", "price": 3500},
        {"nameFr": "Huile d'arachide (1L)", "nameWolof": "Tuti gerte", "unit": "bouteille", "price": 1500},
        {"nameFr": "Sucre (sac 50kg)", "nameWolof": "Sukkar", "unit": "sac", "price": 35000},
        {"nameFr": "Sucre cristallisé (1kg)", "nameWolof": "Sukkar", "unit": "kg", "price": 700},
        {"nameFr": "Sel (1kg)", "nameWolof": "Sel", "unit": "kg", "price": 200},
        {"nameFr": "Sel iodé", "nameWolof": "Sel iodé", "unit": "paquet", "price": 250},
        {"nameFr": "Farine de blé (1kg)", "nameWolof": "Farine", "unit": "kg", "price": 500},
        {"nameFr": "Farine de maïs", "nameWolof": "Farine mburu", "unit": "kg", "price": 400},
        {"nameFr": "Concentré de tomate", "nameWolof": "Concentré", "unit": "boîte", "price": 300},
        {"nameFr": "Sauce tomate", "nameWolof": "Sauce tomate", "unit": "bouteille", "price": 800},
        {"nameFr": "Moutarde", "nameWolof": "Moutarde", "unit": "pot", "price": 600},
        {"nameFr": "Mayonnaise", "nameWolof": "Mayonnaise", "unit": "pot", "price": 800},
        {"nameFr": "Ketchup", "nameWolof": "Ketchup", "unit": "bouteille", "price": 700},
        {"nameFr": "Vinaigre", "nameWolof": "Vinaigre", "unit": "bouteille", "price": 400},
        {"nameFr": "Cube Maggi", "nameWolof": "Maggi", "unit": "boîte", "price": 300},
        {"nameFr": "Cube Jumbo", "nameWolof": "Jumbo", "unit": "boîte", "price": 350},
        {"nameFr": "Poivre noir", "nameWolof": "Poivre", "unit": "paquet", "price": 500},
        {"nameFr": "Piment en poudre", "nameWolof": "Piment", "unit": "sachet", "price": 300},
        {"nameFr": "Curry", "nameWolof": "Curry", "unit": "pot", "price": 400},
        {"nameFr": "Thym", "nameWolof": "Thym", "unit": "sachet", "price": 200},
        {"nameFr": "Laurier", "nameWolof": "Laurier", "unit": "sachet", "price": 200},
        {"nameFr": "Haricots secs", "nameWolof": "Niébé", "unit": "kg", "price": 800},
        {"nameFr": "Lentilles", "nameWolof": "Lentilles", "unit": "kg", "price": 900},
        {"nameFr": "Pois chiches", "nameWolof": "Pois chiches", "unit": "kg", "price": 1000},
        {"nameFr": "Confiture fraise", "nameWolof": "Confiture", "unit": "pot", "price": 1200},
        {"nameFr": "Miel", "nameWolof": "Miel", "unit": "pot", "price": 2500},
        {"nameFr": "Thon en boîte", "nameWolof": "Thon", "unit": "boîte", "price": 800},
        {"nameFr": "Sardines en boîte", "nameWolof": "Sardines", "unit": "boîte", "price": 500},
        {"nameFr": "Maquereau en boîte", "nameWolof": "Maquereau", "unit": "boîte", "price": 600},
        {"nameFr": "Maïs en boîte", "nameWolof": "Maïs", "unit": "boîte", "price": 400},
        {"nameFr": "Petits pois en boîte", "nameWolof": "Petits pois", "unit": "boîte", "price": 450},
        {"nameFr": "Haricots rouges boîte", "nameWolof": "Haricots", "unit": "boîte", "price": 400},
        {"nameFr": "Chocolat en poudre", "nameWolof": "Chocolat", "unit": "boîte", "price": 1500},
        {"nameFr": "Nescafé", "nameWolof": "Nescafé", "unit": "pot", "price": 2000},
        {"nameFr": "Café moulu", "nameWolof": "Café", "unit": "paquet", "price": 1200},
        {"nameFr": "Thé Lipton", "nameWolof": "Ataya Lipton", "unit": "boîte", "price": 800},
        {"nameFr": "Thé vert", "nameWolof": "Ataya vert", "unit": "paquet", "price": 1000},
        {"nameFr": "Biscottes", "nameWolof": "Biscottes", "unit": "paquet", "price": 600},
        {"nameFr": "Céréales petit-déjeuner", "nameWolof": "Céréales", "unit": "boîte", "price": 2000},
        {"nameFr": "Lait en poudre (400g)", "nameWolof": "Meew poudre", "unit": "boîte", "price": 2500},
        {"nameFr": "Lait concentré sucré", "nameWolof": "Lait concentré", "unit": "boîte", "price": 400},
        {"nameFr": "Arachide grillée", "nameWolof": "Gerte rôti", "unit": "kg", "price": 1000},
        {"nameFr": "Noix de cajou", "nameWolof": "Noix cajou", "unit": "kg", "price": 3000},
        {"nameFr": "Amandes", "nameWolof": "Amandes", "unit": "kg", "price": 4000},
        {"nameFr": "Dates", "nameWolof": "Dates", "unit": "kg", "price": 2000},
        {"nameFr": "Raisins secs", "nameWolof": "Raisins secs", "unit": "paquet", "price": 1500},
        {"nameFr": "Chips", "nameWolof": "Chips", "unit": "sachet", "price": 500},
        {"nameFr": "Biscuits salés", "nameWolof": "Biscuits", "unit": "paquet", "price": 400},
    ],
    "boissons": [
        {"nameFr": "Eau minérale (1.5L)", "nameWolof": "Ndox", "unit": "bouteille", "price": 400},
        {"nameFr": "Eau Kirène (pack 6x1.5L)", "nameWolof": "Ndox Kirène", "unit": "pack", "price": 2200},
        {"nameFr": "Eau gazeuse", "nameWolof": "Ndox gazeuse", "unit": "bouteille", "price": 500},
        {"nameFr": "Coca-Cola (1.5L)", "nameWolof": "Coca", "unit": "bouteille", "price": 800},
        {"nameFr": "Coca-Cola (canette)", "nameWolof": "Coca canette", "unit": "unité", "price": 400},
        {"nameFr": "Fanta (1.5L)", "nameWolof": "Fanta", "unit": "bouteille", "price": 800},
        {"nameFr": "Sprite (1.5L)", "nameWolof": "Sprite", "unit": "bouteille", "price": 800},
        {"nameFr": "Gazelle (1.5L)", "nameWolof": "Gazelle", "unit": "bouteille", "price": 700},
        {"nameFr": "Bissap canette", "nameWolof": "Bissap", "unit": "canette", "price": 400},
        {"nameFr": "Jus d'orange (1L)", "nameWolof": "Jus orange", "unit": "bouteille", "price": 1000},
        {"nameFr": "Jus de mangue", "nameWolof": "Jus mango", "unit": "bouteille", "price": 1000},
        {"nameFr": "Jus de pomme", "nameWolof": "Jus pom", "unit": "bouteille", "price": 1200},
        {"nameFr": "Jus d'ananas", "nameWolof": "Jus ananas", "unit": "bouteille", "price": 1000},
        {"nameFr": "Jus multifruits", "nameWolof": "Jus fruits", "unit": "bouteille", "price": 1100},
        {"nameFr": "Jus Bingo", "nameWolof": "Bingo", "unit": "sachet", "price": 100},
        {"nameFr": "Tampico", "nameWolof": "Tampico", "unit": "bouteille", "price": 600},
        {"nameFr": "Pulpy Orange", "nameWolof": "Pulpy", "unit": "bouteille", "price": 500},
        {"nameFr": "Ice Tea", "nameWolof": "Ice Tea", "unit": "bouteille", "price": 600},
        {"nameFr": "Red Bull", "nameWolof": "Red Bull", "unit": "canette", "price": 1000},
        {"nameFr": "Monster Energy", "nameWolof": "Monster", "unit": "canette", "price": 1200},
        {"nameFr": "Lait aromatisé", "nameWolof": "Lait aromatisé", "unit": "bouteille", "price": 700},
        {"nameFr": "Yaourt à boire", "nameWolof": "Yaourt boire", "unit": "bouteille", "price": 500},
        {"nameFr": "Café frappé", "nameWolof": "Café frappé", "unit": "bouteille", "price": 800},
        {"nameFr": "Smoothie fruits", "nameWolof": "Smoothie", "unit": "bouteille", "price": 1500},
        {"nameFr": "Bissap fait maison", "nameWolof": "Bissap maison", "unit": "litre", "price": 800},
        {"nameFr": "Bouye (jus baobab)", "nameWolof": "Bouye", "unit": "litre", "price": 1000},
        {"nameFr": "Gingembre", "nameWolof": "Gingembre", "unit": "litre", "price": 800},
        {"nameFr": "Tamarin", "nameWolof": "Dakhar", "unit": "litre", "price": 700},
        {"nameFr": "Lait caillé sucré", "nameWolof": "Lakh sucré", "unit": "litre", "price": 600},
        {"nameFr": "Café Touba", "nameWolof": "Café Touba", "unit": "sachet", "price": 200},
        {"nameFr": "Thé à la menthe", "nameWolof": "Ataya", "unit": "portion", "price": 300},
        {"nameFr": "Eau de coco", "nameWolof": "Ndox coco", "unit": "bouteille", "price": 1000},
        {"nameFr": "Sirop grenadine", "nameWolof": "Sirop", "unit": "bouteille", "price": 1500},
        {"nameFr": "Sirop menthe", "nameWolof": "Sirop menthe", "unit": "bouteille", "price": 1500},
        {"nameFr": "Bière Flag (canette)", "nameWolof": "Flag", "unit": "canette", "price": 600},
        {"nameFr": "Bière Gazelle (bouteille)", "nameWolof": "Bière Gazelle", "unit": "bouteille", "price": 700},
        {"nameFr": "Vin rouge (bouteille)", "nameWolof": "Vin rouge", "unit": "bouteille", "price": 5000},
        {"nameFr": "Vin blanc", "nameWolof": "Vin blanc", "unit": "bouteille", "price": 5000},
        {"nameFr": "Rosé", "nameWolof": "Rosé", "unit": "bouteille", "price": 4500},
        {"nameFr": "Champagne", "nameWolof": "Champagne", "unit": "bouteille", "price": 15000},
        {"nameFr": "Whisky", "nameWolof": "Whisky", "unit": "bouteille", "price": 12000},
        {"nameFr": "Vodka", "nameWolof": "Vodka", "unit": "bouteille", "price": 8000},
        {"nameFr": "Rhum", "nameWolof": "Rhum", "unit": "bouteille", "price": 7000},
        {"nameFr": "Gin", "nameWolof": "Gin", "unit": "bouteille", "price": 9000},
        {"nameFr": "Liqueur", "nameWolof": "Liqueur", "unit": "bouteille", "price": 6000},
        {"nameFr": "Cidre", "nameWolof": "Cidre", "unit": "bouteille", "price": 3000},
        {"nameFr": "Mojito (non-alcoolisé)", "nameWolof": "Mojito", "unit": "verre", "price": 1500},
        {"nameFr": "Milkshake vanille", "nameWolof": "Milkshake", "unit": "verre", "price": 1500},
        {"nameFr": "Chocolat chaud", "nameWolof": "Chocolat chaud", "unit": "tasse", "price": 800},
        {"nameFr": "Cappuccino", "nameWolof": "Cappuccino", "unit": "tasse", "price": 1000},
    ],
    "hygiene_bazar": [
        {"nameFr": "Savon de Marseille", "nameWolof": "Saabu", "unit": "morceau", "price": 500},
        {"nameFr": "Savon liquide", "nameWolof": "Saabu liquide", "unit": "bouteille", "price": 1500},
        {"nameFr": "Shampoing", "nameWolof": "Shampoing", "unit": "bouteille", "price": 2000},
        {"nameFr": "Gel douche", "nameWolof": "Gel douche", "unit": "bouteille", "price": 1800},
        {"nameFr": "Dentifrice", "nameWolof": "Dentifrice", "unit": "tube", "price": 800},
        {"nameFr": "Brosse à dents", "nameWolof": "Brosse dents", "unit": "unité", "price": 500},
        {"nameFr": "Déodorant", "nameWolof": "Déodorant", "unit": "flacon", "price": 1500},
        {"nameFr": "Crème hydratante", "nameWolof": "Crème", "unit": "pot", "price": 2000},
        {"nameFr": "Lait de toilette", "nameWolof": "Lait toilette", "unit": "bouteille", "price": 1800},
        {"nameFr": "Parfum", "nameWolof": "Parfum", "unit": "flacon", "price": 5000},
        {"nameFr": "Eau de Cologne", "nameWolof": "Eau Cologne", "unit": "flacon", "price": 2000},
        {"nameFr": "Talc", "nameWolof": "Talc", "unit": "boîte", "price": 800},
        {"nameFr": "Couches bébé", "nameWolof": "Couches", "unit": "paquet", "price": 4000},
        {"nameFr": "Lingettes bébé", "nameWolof": "Lingettes", "unit": "paquet", "price": 1500},
        {"nameFr": "Coton-tige", "nameWolof": "Coton-tige", "unit": "boîte", "price": 500},
        {"nameFr": "Coton démaquillant", "nameWolof": "Coton", "unit": "paquet", "price": 800},
        {"nameFr": "Rasoir", "nameWolof": "Rasoir", "unit": "paquet", "price": 1000},
        {"nameFr": "Mousse à raser", "nameWolof": "Mousse raser", "unit": "bombe", "price": 1500},
        {"nameFr": "Après-rasage", "nameWolof": "Après-rasage", "unit": "flacon", "price": 2000},
        {"nameFr": "Papier toilette", "nameWolof": "Papier toilette", "unit": "paquet", "price": 2500},
        {"nameFr": "Mouchoirs en papier", "nameWolof": "Mouchoirs", "unit": "boîte", "price": 600},
        {"nameFr": "Serviettes hygiéniques", "nameWolof": "Serviettes", "unit": "paquet", "price": 1500},
        {"nameFr": "Tampons", "nameWolof": "Tampons", "unit": "boîte", "price": 1800},
        {"nameFr": "Lessive en poudre", "nameWolof": "Lessive", "unit": "paquet", "price": 3000},
        {"nameFr": "Lessive liquide", "nameWolof": "Lessive liquide", "unit": "bouteille", "price": 3500},
        {"nameFr": "Eau de Javel", "nameWolof": "Javel", "unit": "bouteille", "price": 800},
        {"nameFr": "Désinfectant", "nameWolof": "Désinfectant", "unit": "bouteille", "price": 1500},
        {"nameFr": "Nettoyant sol", "nameWolof": "Nettoyant", "unit": "bouteille", "price": 1200},
        {"nameFr": "Liquide vaisselle", "nameWolof": "Liquide vaisselle", "unit": "bouteille", "price": 1000},
        {"nameFr": "Éponges", "nameWolof": "Éponges", "unit": "paquet", "price": 500},
        {"nameFr": "Gants de ménage", "nameWolof": "Gants", "unit": "paire", "price": 600},
        {"nameFr": "Balai", "nameWolof": "Balai", "unit": "unité", "price": 2000},
        {"nameFr": "Serpillière", "nameWolof": "Serpillière", "unit": "unité", "price": 1000},
        {"nameFr": "Seau", "nameWolof": "Seau", "unit": "unité", "price": 1500},
        {"nameFr": "Bassine", "nameWolof": "Bassine", "unit": "unité", "price": 1200},
        {"nameFr": "Poubelle", "nameWolof": "Poubelle", "unit": "unité", "price": 3000},
        {"nameFr": "Sacs poubelle", "nameWolof": "Sacs poubelle", "unit": "rouleau", "price": 1000},
        {"nameFr": "Allumettes", "nameWolof": "Allumettes", "unit": "boîte", "price": 100},
        {"nameFr": "Briquet", "nameWolof": "Briquet", "unit": "unité", "price": 200},
        {"nameFr": "Bougies", "nameWolof": "Bougies", "unit": "paquet", "price": 500},
    ],
    "energie_tech": [
        {"nameFr": "Pile AA", "nameWolof": "Pile AA", "unit": "paquet", "price": 1000},
        {"nameFr": "Pile AAA", "nameWolof": "Pile AAA", "unit": "paquet", "price": 1000},
        {"nameFr": "Pile 9V", "nameWolof": "Pile 9V", "unit": "unité", "price": 500},
        {"nameFr": "Lampe torche", "nameWolof": "Lampe torche", "unit": "unité", "price": 2000},
        {"nameFr": "Ampoule LED", "nameWolof": "Ampoule LED", "unit": "unité", "price": 1500},
        {"nameFr": "Ampoule économique", "nameWolof": "Ampoule eco", "unit": "unité", "price": 1000},
        {"nameFr": "Rallonge électrique", "nameWolof": "Rallonge", "unit": "unité", "price": 3000},
        {"nameFr": "Multiprise", "nameWolof": "Multiprise", "unit": "unité", "price": 2500},
        {"nameFr": "Adaptateur universel", "nameWolof": "Adaptateur", "unit": "unité", "price": 2000},
        {"nameFr": "Chargeur USB", "nameWolof": "Chargeur USB", "unit": "unité", "price": 3000},
        {"nameFr": "Câble USB-C", "nameWolof": "Câble USB-C", "unit": "unité", "price": 1500},
        {"nameFr": "Câble micro-USB", "nameWolof": "Câble micro-USB", "unit": "unité", "price": 1000},
        {"nameFr": "Câble Lightning", "nameWolof": "Câble Lightning", "unit": "unité", "price": 2000},
        {"nameFr": "Écouteurs", "nameWolof": "Écouteurs", "unit": "unité", "price": 2000},
        {"nameFr": "Casque audio", "nameWolof": "Casque", "unit": "unité", "price": 5000},
        {"nameFr": "Enceinte Bluetooth", "nameWolof": "Enceinte Bluetooth", "unit": "unité", "price": 10000},
        {"nameFr": "Powerbank 10000mAh", "nameWolof": "Powerbank", "unit": "unité", "price": 8000},
        {"nameFr": "Clé USB 32GB", "nameWolof": "Clé USB", "unit": "unité", "price": 5000},
        {"nameFr": "Carte mémoire 64GB", "nameWolof": "Carte mémoire", "unit": "unité", "price": 8000},
        {"nameFr": "Souris sans fil", "nameWolof": "Souris", "unit": "unité", "price": 5000},
        {"nameFr": "Clavier sans fil", "nameWolof": "Clavier", "unit": "unité", "price": 8000},
        {"nameFr": "Webcam", "nameWolof": "Webcam", "unit": "unité", "price": 15000},
        {"nameFr": "Protection écran phone", "nameWolof": "Protection écran", "unit": "unité", "price": 2000},
        {"nameFr": "Coque téléphone", "nameWolof": "Coque phone", "unit": "unité", "price": 2500},
        {"nameFr": "Support téléphone", "nameWolof": "Support phone", "unit": "unité", "price": 3000},
        {"nameFr": "Lampe de bureau LED", "nameWolof": "Lampe bureau", "unit": "unité", "price": 8000},
        {"nameFr": "Ventilateur USB", "nameWolof": "Ventilateur USB", "unit": "unité", "price": 3000},
        {"nameFr": "Prise programmable", "nameWolof": "Prise programmable", "unit": "unité", "price": 5000},
        {"nameFr": "Détecteur de fumée", "nameWolof": "Détecteur fumée", "unit": "unité", "price": 10000},
        {"nameFr": "Thermomètre digital", "nameWolof": "Thermomètre", "unit": "unité", "price": 3000},
    ],
    "quincaillerie": [
        {"nameFr": "Marteau", "nameWolof": "Marteau", "unit": "unité", "price": 3000},
        {"nameFr": "Tournevis plat", "nameWolof": "Tournevis plat", "unit": "unité", "price": 1000},
        {"nameFr": "Tournevis cruciforme", "nameWolof": "Tournevis cruciforme", "unit": "unité", "price": 1000},
        {"nameFr": "Clé à molette", "nameWolof": "Clé molette", "unit": "unité", "price": 2500},
        {"nameFr": "Pince multiprise", "nameWolof": "Pince", "unit": "unité", "price": 2000},
        {"nameFr": "Scie à main", "nameWolof": "Scie", "unit": "unité", "price": 4000},
        {"nameFr": "Niveau à bulle", "nameWolof": "Niveau", "unit": "unité", "price": 2000},
        {"nameFr": "Mètre ruban 5m", "nameWolof": "Mètre", "unit": "unité", "price": 1500},
        {"nameFr": "Cutter", "nameWolof": "Cutter", "unit": "unité", "price": 500},
        {"nameFr": "Lime", "nameWolof": "Lima", "unit": "unité", "price": 1000},
        {"nameFr": "Râpe", "nameWolof": "Râpe", "unit": "unité", "price": 1200},
        {"nameFr": "Perceuse électrique", "nameWolof": "Perceuse", "unit": "unité", "price": 35000},
        {"nameFr": "Forets (set)", "nameWolof": "Forets", "unit": "set", "price": 5000},
        {"nameFr": "Clous (1kg)", "nameWolof": "Clous", "unit": "kg", "price": 2000},
        {"nameFr": "Vis (boîte)", "nameWolof": "Vis", "unit": "boîte", "price": 2500},
        {"nameFr": "Chevilles (boîte)", "nameWolof": "Chevilles", "unit": "boîte", "price": 1500},
        {"nameFr": "Colle bois", "nameWolof": "Colle bois", "unit": "tube", "price": 1000},
        {"nameFr": "Colle universelle", "nameWolof": "Colle", "unit": "tube", "price": 800},
        {"nameFr": "Silicone", "nameWolof": "Silicone", "unit": "cartouche", "price": 1500},
        {"nameFr": "Ruban adhésif", "nameWolof": "Scotch", "unit": "rouleau", "price": 500},
        {"nameFr": "Ruban isolant", "nameWolof": "Ruban isolant", "unit": "rouleau", "price": 600},
        {"nameFr": "Corde nylon 10m", "nameWolof": "Corde", "unit": "rouleau", "price": 2000},
        {"nameFr": "Chaîne métal 1m", "nameWolof": "Chaîne", "unit": "mètre", "price": 1500},
        {"nameFr": "Cadenas", "nameWolof": "Cadenas", "unit": "unité", "price": 2000},
        {"nameFr": "Verrou de porte", "nameWolof": "Verrou", "unit": "unité", "price": 1500},
        {"nameFr": "Poignée de porte", "nameWolof": "Poignée", "unit": "unité", "price": 3000},
        {"nameFr": "Charnières", "nameWolof": "Charnières", "unit": "paire", "price": 1000},
        {"nameFr": "Peinture blanche (1L)", "nameWolof": "Peinture blanc", "unit": "pot", "price": 5000},
        {"nameFr": "Peinture couleur (1L)", "nameWolof": "Peinture couleur", "unit": "pot", "price": 5500},
        {"nameFr": "Pinceau", "nameWolof": "Pinceau", "unit": "unité", "price": 1000},
    ],
    "ustensiles_cuisine": [
        {"nameFr": "Marmite aluminium 10L", "nameWolof": "Canari", "unit": "unité", "price": 5000},
        {"nameFr": "Casserole 5L", "nameWolof": "Casserole", "unit": "unité", "price": 3000},
        {"nameFr": "Poêle anti-adhésive", "nameWolof": "Poêle", "unit": "unité", "price": 4000},
        {"nameFr": "Couvercle universel", "nameWolof": "Couvercle", "unit": "unité", "price": 1000},
        {"nameFr": "Couteau de cuisine", "nameWolof": "Paal", "unit": "unité", "price": 2000},
        {"nameFr": "Planche à découper", "nameWolof": "Planche", "unit": "unité", "price": 1500},
        {"nameFr": "Louche", "nameWolof": "Louche", "unit": "unité", "price": 500},
        {"nameFr": "Spatule", "nameWolof": "Spatule", "unit": "unité", "price": 400},
        {"nameFr": "Cuillère en bois", "nameWolof": "Cuillère bois", "unit": "unité", "price": 300},
        {"nameFr": "Passoire", "nameWolof": "Passoire", "unit": "unité", "price": 1000},
        {"nameFr": "Saladier", "nameWolof": "Saladier", "unit": "unité", "price": 2000},
        {"nameFr": "Bol", "nameWolof": "Bol", "unit": "unité", "price": 500},
        {"nameFr": "Assiette plate", "nameWolof": "Assiette", "unit": "unité", "price": 500},
        {"nameFr": "Assiette creuse", "nameWolof": "Assiette creuse", "unit": "unité", "price": 600},
        {"nameFr": "Verre", "nameWolof": "Verre", "unit": "unité", "price": 300},
        {"nameFr": "Tasse", "nameWolof": "Tasse", "unit": "unité", "price": 400},
        {"nameFr": "Fourchette", "nameWolof": "Fourchette", "unit": "unité", "price": 200},
        {"nameFr": "Cuillère à soupe", "nameWolof": "Cuillère soupe", "unit": "unité", "price": 200},
        {"nameFr": "Couteau de table", "nameWolof": "Couteau table", "unit": "unité", "price": 250},
        {"nameFr": "Plateau", "nameWolof": "Plateau", "unit": "unité", "price": 2000},
        {"nameFr": "Théière", "nameWolof": "Théière", "unit": "unité", "price": 3000},
        {"nameFr": "Cafetière", "nameWolof": "Cafetière", "unit": "unité", "price": 5000},
        {"nameFr": "Bouilloire", "nameWolof": "Bouilloire", "unit": "unité", "price": 4000},
        {"nameFr": "Mixeur", "nameWolof": "Mixeur", "unit": "unité", "price": 15000},
        {"nameFr": "Moulin à épices", "nameWolof": "Moulin", "unit": "unité", "price": 3000},
        {"nameFr": "Râpe fromage", "nameWolof": "Râpe", "unit": "unité", "price": 1000},
        {"nameFr": "Ouvre-boîte", "nameWolof": "Ouvre-boîte", "unit": "unité", "price": 500},
        {"nameFr": "Décapsuleur", "nameWolof": "Décapsuleur", "unit": "unité", "price": 300},
        {"nameFr": "Tire-bouchon", "nameWolof": "Tire-bouchon", "unit": "unité", "price": 800},
        {"nameFr": "Tupperware (set 3)", "nameWolof": "Tupperware", "unit": "set", "price": 3000},
    ],
    "materiaux_construction": [
        {"nameFr": "Ciment (sac 50kg)", "nameWolof": "Ciment", "unit": "sac", "price": 5000},
        {"nameFr": "Sable (m³)", "nameWolof": "Sëbël", "unit": "m³", "price": 15000},
        {"nameFr": "Gravier (m³)", "nameWolof": "Gravier", "unit": "m³", "price": 18000},
        {"nameFr": "Brique creuse", "nameWolof": "Brique", "unit": "unité", "price": 150},
        {"nameFr": "Parpaing 15", "nameWolof": "Parpaing", "unit": "unité", "price": 250},
        {"nameFr": "Parpaing 20", "nameWolof": "Parpaing 20", "unit": "unité", "price": 300},
        {"nameFr": "Fer à béton 8mm", "nameWolof": "Fer 8", "unit": "barre", "price": 4000},
        {"nameFr": "Fer à béton 10mm", "nameWolof": "Fer 10", "unit": "barre", "price": 5500},
        {"nameFr": "Fer à béton 12mm", "nameWolof": "Fer 12", "unit": "barre", "price": 7000},
        {"nameFr": "Fil à ligaturer", "nameWolof": "Fil ligaturer", "unit": "kg", "price": 1500},
        {"nameFr": "Carreau 30x30", "nameWolof": "Carreau", "unit": "m²", "price": 8000},
        {"nameFr": "Carreau 40x40", "nameWolof": "Carreau 40", "unit": "m²", "price": 12000},
        {"nameFr": "Faïence murale", "nameWolof": "Faïence", "unit": "m²", "price": 10000},
        {"nameFr": "Ciment-colle", "nameWolof": "Ciment-colle", "unit": "sac", "price": 4000},
        {"nameFr": "Joint carrelage", "nameWolof": "Joint", "unit": "sac", "price": 2000},
        {"nameFr": "Plâtre (sac 25kg)", "nameWolof": "Plâtre", "unit": "sac", "price": 3000},
        {"nameFr": "Tuyau PVC 32mm", "nameWolof": "Tuyau PVC", "unit": "barre", "price": 2000},
        {"nameFr": "Tuyau PVC 50mm", "nameWolof": "Tuyau 50", "unit": "barre", "price": 3000},
        {"nameFr": "Tuyau PVC 100mm", "nameWolof": "Tuyau 100", "unit": "barre", "price": 5000},
        {"nameFr": "Coude PVC 90°", "nameWolof": "Coude", "unit": "unité", "price": 500},
        {"nameFr": "Robinet lavabo", "nameWolof": "Robinet", "unit": "unité", "price": 8000},
        {"nameFr": "Robinet jardin", "nameWolof": "Robinet jardin", "unit": "unité", "price": 3000},
        {"nameFr": "WC complet", "nameWolof": "WC", "unit": "unité", "price": 50000},
        {"nameFr": "Lavabo", "nameWolof": "Lavabo", "unit": "unité", "price": 25000},
        {"nameFr": "Évier inox", "nameWolof": "Évier", "unit": "unité", "price": 30000},
        {"nameFr": "Porte en bois", "nameWolof": "Bunt", "unit": "unité", "price": 40000},
        {"nameFr": "Fenêtre aluminium", "nameWolof": "Fenêtre", "unit": "unité", "price": 35000},
        {"nameFr": "Grillage 1m hauteur", "nameWolof": "Grillage", "unit": "rouleau", "price": 25000},
        {"nameFr": "Fil barbelé", "nameWolof": "Fil barbelé", "unit": "rouleau", "price": 15000},
        {"nameFr": "Tôle ondulée", "nameWolof": "Tôle", "unit": "feuille", "price": 12000},
    ],
    "mobilier": [
        {"nameFr": "Matelas mousse 140x190", "nameWolof": "Matelas", "unit": "unité", "price": 50000},
        {"nameFr": "Matelas mousse 90x190", "nameWolof": "Matelas simple", "unit": "unité", "price": 35000},
        {"nameFr": "Sommier 140x190", "nameWolof": "Sommier", "unit": "unité", "price": 40000},
        {"nameFr": "Lit en bois double", "nameWolof": "Lit double", "unit": "unité", "price": 80000},
        {"nameFr": "Lit simple", "nameWolof": "Lit simple", "unit": "unité", "price": 50000},
        {"nameFr": "Armoire 3 portes", "nameWolof": "Armoire", "unit": "unité", "price": 120000},
        {"nameFr": "Commode", "nameWolof": "Commode", "unit": "unité", "price": 60000},
        {"nameFr": "Table de chevet", "nameWolof": "Table chevet", "unit": "unité", "price": 25000},
        {"nameFr": "Table à manger 6 places", "nameWolof": "Table manger", "unit": "unité", "price": 100000},
        {"nameFr": "Chaise en bois", "nameWolof": "Chaise bois", "unit": "unité", "price": 15000},
        {"nameFr": "Chaise plastique", "nameWolof": "Chaise plastique", "unit": "unité", "price": 5000},
        {"nameFr": "Tabouret", "nameWolof": "Tabouret", "unit": "unité", "price": 8000},
        {"nameFr": "Canapé 3 places", "nameWolof": "Canapé", "unit": "unité", "price": 200000},
        {"nameFr": "Fauteuil", "nameWolof": "Fauteuil", "unit": "unité", "price": 70000},
        {"nameFr": "Table basse", "nameWolof": "Table basse", "unit": "unité", "price": 40000},
        {"nameFr": "Étagère murale", "nameWolof": "Étagère", "unit": "unité", "price": 30000},
        {"nameFr": "Bibliothèque", "nameWolof": "Bibliothèque", "unit": "unité", "price": 80000},
        {"nameFr": "Bureau informatique", "nameWolof": "Bureau", "unit": "unité", "price": 60000},
        {"nameFr": "Chaise de bureau", "nameWolof": "Chaise bureau", "unit": "unité", "price": 35000},
        {"nameFr": "Meuble TV", "nameWolof": "Meuble TV", "unit": "unité", "price": 50000},
        {"nameFr": "Miroir mural", "nameWolof": "Miroir", "unit": "unité", "price": 15000},
        {"nameFr": "Lampe de salon", "nameWolof": "Lampe salon", "unit": "unité", "price": 12000},
        {"nameFr": "Ventilateur sur pied", "nameWolof": "Ventilateur pied", "unit": "unité", "price": 25000},
        {"nameFr": "Ventilateur plafond", "nameWolof": "Ventilateur plafond", "unit": "unité", "price": 30000},
        {"nameFr": "Rideau 2m", "nameWolof": "Rideau", "unit": "paire", "price": 15000},
        {"nameFr": "Tapis 2x3m", "nameWolof": "Tapis", "unit": "unité", "price": 25000},
        {"nameFr": "Coussin décoratif", "nameWolof": "Coussin", "unit": "unité", "price": 5000},
        {"nameFr": "Porte-manteau", "nameWolof": "Porte-manteau", "unit": "unité", "price": 10000},
        {"nameFr": "Panier à linge", "nameWolof": "Panier linge", "unit": "unité", "price": 5000},
        {"nameFr": "Cintre (lot 10)", "nameWolof": "Cintre", "unit": "lot", "price": 2000},
    ],
}

async def seed_database():
    """Seed la base de données avec les produits par défaut"""
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("🌱 Début du seeding de la base de données Bor-bi Tech...")
    
    # Clear existing data
    await db.default_products.delete_many({})
    print("✅ Anciennes données supprimées")
    
    # Insert products
    total_products = 0
    for category, products in PRODUCTS_DATA.items():
        for product in products:
            doc = {
                "nameFr": product["nameFr"],
                "nameWolof": product["nameWolof"],
                "category": category,
                "unit": product["unit"],
                "defaultPrice": product["price"],
                "brand": product.get("brand"),
                "imageUrl": f"https://via.placeholder.com/150?text={product['nameFr'][:20]}",
                "createdAt": datetime.utcnow()
            }
            await db.default_products.insert_one(doc)
            total_products += 1
    
    print(f"✅ {total_products} produits insérés dans la base de données")
    print(f"📦 Catégories créées : {list(PRODUCTS_DATA.keys())}")
    
    # Create indexes
    await db.default_products.create_index("category")
    await db.default_products.create_index("nameFr")
    await db.users.create_index("email", unique=True, sparse=True)
    await db.users.create_index("phone", unique=True, sparse=True)
    await db.transactions.create_index("hash", unique=True)
    await db.messages.create_index([("senderId", 1), ("receiverId", 1)])
    await db.messages.create_index([("receiverId", 1), ("read", 1)])
    
    print("✅ Index créés")
    print("🎉 Seeding terminé avec succès!")
    
    client.close()

if __name__ == "__main__":
    asyncio.run(seed_database())
